### PR TITLE
Resolve return-type errors for Bugfix/1167

### LINKED ISSUE #1167: Potential Undefined Behavior in object.c
Initial Checklist prior to submitting the issue. Check the bellow boxes to the best of your knowledge:

- [X] I have not found an open issue describing the same problem.
- [X] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [X] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------

## Please describe what was the cause of the issue?
`set_rank` and `_set_rankx` in object.c are both declared as having `static int` return type, but both exit flow control without returning any value in at least a portion of run cases. 

According to the C11 standard (2018 standard is behind paywall, but this definition should not have changed):
> If the } that terminates a function is reached, and the value of the function call is used by
the caller, the behavior is undefined.
[N1570, C11 Standard, Page 157, item 12](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf)

Based on the standard, and the current use of the functions listed, the current behavior of Gridlab-d may be undefined. 

## Please provide the steps to reproduce.
n/a - does not currently cause an error.

## Please provide the exact error/warning/failure message printed on the console.
n/a - does not currently cause an error.

## If possible, please provide any screenshots and other supporting information.
This should be a fairly trivial bug to actually fix, but it is important that we're returning values that are sane for all cases, so I've tagged a number of individuals who may be able to provide feedback as to "safe/sane" values to select as the default return case.

-------------------------------------------------------------------------------------------------------------

### LINKED ISSUE #1193: MacOS and Ubuntu Linux optimized release builds segfault on completion
MacOS and Ubuntu Linux optimized release builds segfault on completion

Text:
- [X] I have not found an open issue describing the same problem.
- [X] I went through "CONTRIBUTING.MD" before deciding to submit the issue.
- [X] While building GridLAB-D, I followed all steps as detailed in GridLAB-D Wiki.

------------------------------------------------------------------------------------------------------------
Building versions of GridLAB-D based on /develop and master (4.1) seem to have issues with optimization turned on and GridLAB-D exiting.  On MacOS builds (High Sierra - Homebrew GCC 8.2.0 and Homebrew GCC 9) and Ubuntu 19.04 builds (GCC 8.3.0), if optimization is set above 0 (so O1 or O2), GridLAB-D produces a segmentation fault on exit.  At O0 (no optimization), no segfault occurs.  No segfaults appear to occur under Windows MSYS2 builds (GCC 9.1.0) - that build exits fine, even at O2 optimization.

On MacOS and Ubuntu, the GLM appears to complete, and a select examination of autotests indicates they still are getting correct answers, they just fail on exit (so the validate procedure fails, due to segfaults at the end)

This only appears to happen when GridLAB-D runs a GLM.  With a --version or just running it empty (to get the webpage to open), no segfault appears.

## Please describe what was the cause of the issue?
Running GridLAB-D with a GLM file seems to produce it. 

## Please provide the steps to reproduce.
Run GridLAB-D with a GLM file.  It seems to occur 100% of the time on an optimized build.

## Please provide the exact error/warning/failure message printed on the console.
Ubuntu Linux - "Segmentation fault (core dumped)"
MacOS - "Segmentation fault: 11"

## If possible, please provide any screenshots and other supporting information.

-------------------------------------------------------------------------------------------------------------

### PR DESCRIPTION
**Pull request by eberleim**
#### What's this Pull Request do?
This PR fixes a class of undefined behavior throughout GridLAB-D's codebase where functions declared to return a type contain a flow-path by which it is possible to reach the end of flow control without returning a value. 
This behavior caused optimized builds to fail and segmentation fault. 

#### Where should the reviewer start?
Verify the application compiles, installs, and runs successfully using any compilers commonly used with the reviewer's use-case, including with optimizations enabled. 
Additionally, review values selected as return types, and confirm if they are reasonable default return values, for any paths where flow control allows that return to occur (note: some returns are unreachable, and exist purely to satisfy the compiler). 

This has already been tested up to `-O2` on:
-MSYS2 using GCC 9
-Ubuntu 18.04 using GCC 7
-MacOS using Homebrew GCC 8

#### Any background context you want to provide?
This particular category of undefined behavior causes the Segmentation Faults as identified in #1193 and #1167, among other possible related issues. 

#### What are the relevant issues?
Resolves #1167 
Resolves #1193

### CODE REVIEW

File: market/auction.cpp [hunk 1]
```diff
@@ -1598,8 +1598,8 @@ int auction::submit_nolock(char *from, double quantity, double real_price, KEY k
 				gl_name(OBJECTHDR(this),myname,sizeof(myname)),quantity<0?"ask":"offer",
 				from);
 		}
-		return 1;
 	}
+	return 1;
```
Comment (dchassin) [inline market/auction.cpp]: I think this one should be return 0. It looks like a fall-through case.

Comment (eberleim) [reply market/auction.cpp]: Changed in auction and auction_ccsi to return 0 in fall-through case. Thanks!

File: gldcore/object.c [hunk 2]
```diff
@@ -1212,7 +1212,7 @@ OBJECT *object_get_next(OBJECT *obj){ /**< the object from which to start */
 	the request to prevent looping.  This will prevent
 	an object_set_parent call from creating a parent loop.
  */
-static int _set_rank(OBJECT *obj, OBJECTRANK rank, OBJECT *first)
+static unsigned int _set_rank(OBJECT *obj, OBJECTRANK rank, OBJECT *first)
```
Comment (ftuffner) [inline gldcore/object.c]: So OBJECTRANK is an unsigned and this makes sense, but will the various `return -1;` error conditions cause any issues with this?

Comment (eberleim) [reply gldcore/object.c]: Strictly speaking, casting -1 to unsigned int will produce UINT_MAX, which would be a valid value. I would classify this as an altogether separate bug. 
our options are probably to change the error detection value to be UINT_MAX, or change OBJECTRANK to be signed.

File: market/auction.cpp [hunk 3]
```diff
@@ -1598,8 +1598,8 @@ int auction::submit_nolock(char *from, double quantity, double real_price, KEY k
 				gl_name(OBJECTHDR(this),myname,sizeof(myname)),quantity<0?"ask":"offer",
 				from);
 		}
-		return 1;
```
Comment (ftuffner) [inline market/auction.cpp]: Defer to review from @dchassin on this one.  Old market bid will now pass a fail, which seems correct, but not sure if that will break anything.

File: gldcore/object.c (hunk 2 above)
Comment (ftuffner) [reply gldcore/object.c]: Fair enough.  As long as we never have UINT_MAX objects/ranks, it shouldn't have any ambiguity.

**Comment by eberleim** [comment]
@ftuffner @afisher1 Is there any realistic situation where `OBJECTRANK` would exceed 32-bit int max (2,147,483,647)? If not, to make sure -1 still triggers an error, I think changing `OBJECTRANK` from unsigned to regular int is probably the best approach.
